//
// automatically generated by spin2cpp v1.01 on Wed Dec 12 21:35:05 2012
// spin2cpp.linux --main test_nl.spin 
//

#ifndef fsrwSpin_Class_Defined__
#define fsrwSpin_Class_Defined__

#include <stdint.h>
#include "safe_spi.h"

class fsrwSpin {
public:
  static const int Sectorsize = 512;
  static const int Sectorshift = 9;
  static const int Dirsize = 32;
  static const int Dirshift = 5;
  safe_spi	Sdspi;
  int32_t	Release(void);
  int32_t	Unmount(void);
  int32_t	Mount_explicit(int32_t Do, int32_t Clk, int32_t Di, int32_t Cs);
  int32_t	Mount(int32_t Basepin);
  int32_t	Pflush(void);
  int32_t	Pclose(void);
  int32_t	Setdate(int32_t Year, int32_t Month, int32_t Day, int32_t Hour, int32_t Minute, int32_t Second);
  int32_t	Popen(int32_t S, int32_t Mode);
  int32_t	Get_filesize(void);
  int32_t	Pread(int32_t Ubuf, int32_t Count);
  int32_t	Pgetc(void);
  int32_t	Pwrite(int32_t Ubuf, int32_t Count);
  int32_t	Pputs(int32_t B);
  int32_t	Pputc(int32_t C);
  int32_t	Seek(int32_t Pos);
  int32_t	Tell(void);
  int32_t	Opendir(void);
  int32_t	Nextfile(int32_t Fbuf);
  int32_t	Getclustersize(void);
  int32_t	Getclustercount(void);
private:
  int32_t	volatile Fclust;
  int32_t	volatile Filesize;
  int32_t	volatile Floc;
  int32_t	volatile Frem;
  int32_t	volatile Bufat;
  int32_t	volatile Bufend;
  int32_t	volatile Direntry;
  int32_t	volatile Writelink;
  int32_t	volatile Fatptr;
  int32_t	volatile Firstcluster;
  int32_t	volatile Errno;
  int32_t	volatile Filesystem;
  int32_t	volatile Rootdir;
  int32_t	volatile Rootdirend;
  int32_t	volatile Dataregion;
  int32_t	volatile Clustershift;
  int32_t	volatile Clustersize;
  int32_t	volatile Fat1;
  int32_t	volatile Totclusters;
  int32_t	volatile Sectorsperfat;
  int32_t	volatile Endofchain;
  int32_t	volatile Pdate;
  int32_t	volatile Lastread;
  int32_t	volatile Dirty;
  uint8_t	volatile Buf[512];
  uint8_t	volatile Buf2[512];
  uint8_t	volatile Padname[11];
  int32_t	Writeblock2(int32_t N, int32_t B);
  int32_t	Flushifdirty(void);
  int32_t	Readblockc(int32_t N);
  int32_t	Brword(int32_t B);
  int32_t	Brlong(int32_t B);
  int32_t	Brclust(int32_t B);
  int32_t	Brwword(int32_t W, int32_t V);
  int32_t	Brwlong(int32_t W, int32_t V);
  int32_t	Brwclust(int32_t W, int32_t V);
  int32_t	Getfstype(void);
  int32_t	Readbytec(int32_t Byteloc);
  int32_t	Readfat(int32_t Clust);
  int32_t	Followchain(void);
  int32_t	Nextcluster(void);
  int32_t	Freeclusters(int32_t Clust);
  int32_t	Datablock(void);
  int32_t	Uc(int32_t C);
  int32_t	Pflushbuf(int32_t Rcnt, int32_t Metadata);
  int32_t	Pfillbuf(void);
};

#endif
